(define-module (saffronsnail hpc-notes pi)
  #:use-module ((guix build-system gnu)
                (guix download)
                (guix licenses)
                (guix packages)
               )
)

(package
  (name "pi-calculator")
  (version "0.2")
  (source (origin (uri (string-append "file://" (getcwd)))
                  (method url-fetch)
                  (sha256 (system "guix hash -r ."))
          )
  )
  (build-system gnu-build-system)
  (arguments '(#:phases (modify-phases %standard-phases
                                         (replace 'build (lambda* (#:key outputs #:allow-other-keys)
                                           (let ((prefix (cdr (assoc "out" outputs))))
                                             (mkdir prefix)
                                             (= 0 (status:exit-val (system (string-append "PREFIX=" prefix " make"))))
                                           )
                                         ))
                                         (delete 'configure)
                                         (delete 'check)
                                         (delete 'install)
                                         (delete 'patch-shebangs)
                                         (delete 'strip)
                        )
              )
  )
  (synopsis "Calculates pi by inscribing a circle in a square")
  (description "Using random points makes this a rough estimate")
  (license public-domain)
  (home-page 'nil)
)

