(define-module (saffronsnail hpc-notes pi)
  #:use-module (guix packages)
  #:use-module (guix build-system gnu)
)

(package
  (name "pi-calculator")
  (version "0.1")
  (source (origin (uri (string-append "file://" (getcwd)))
                  (method url-fetch)
                  (sha256 (system "guix hash -r ."))
          )
  )
  (build-system gnu-build-system)
  (arguments '(#:phases (modify-phases %standard-phases (delete 'configure)
                                                        (delete 'check)
                                                        (delete 'install)
                                                        (delete 'patch-shebangs)
                                                        (delete 'strip)
                        )
              )
  )
  (synopsis "Calculates pi by inscribing a circle in a square")
  (description "Using random points makes this a rough estimate")
)

